import 'package:clothing_swap/features/clothing/domain/clothing_info.dart';
import 'package:clothing_swap/features/clothing/presentation/preferences_provider.dart';
import 'package:clothing_swap/features/profile/presentation/profile_class.dart';
import 'package:clothing_swap/theme/gradient.dart';
import 'package:clothing_swap/widgets/custom_bottom_nav_bar.dart';
import 'package:clothing_swap/widgets/custom_top_app_bar.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:provider/provider.dart';
import 'package:string_extensions/string_extensions.dart';

//Page for selecting clothing search preferences
class AddClothesPreferences extends StatefulWidget {
  const AddClothesPreferences({super.key, this.category});
  final String? category;

  @override
  State<AddClothesPreferences> createState() => _AddClothesPreferencesState();
}

Map<Enum, FaIcon> _pickCategory(String option) {
  switch (option) {
    case "Type":
      return clothingTypeIcons;
    case "Size":
      return letteredSizeIcons;
    case "Condition":
      return clothingConditionIcons;
    case "Colour":
      return clothingColourIcons;
    case "Gender":
      return clothingGenderIcons;
  }
  return clothingColourIcons;
}

class _AddClothesPreferencesState extends State<AddClothesPreferences> {
  late String categories;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    // GPT suggested using ModalRoute to Extract the 'categories' argument
    categories = ModalRoute.of(context)!.settings.arguments as String;
  }

  void _handlePress(int index, Map<Enum, FaIcon> category, String currentOption,
      PreferencesNotifier preferencesNotifier, List<String> preferences) {
    setState(() {
      if (preferences.contains(currentOption)) {
        preferencesNotifier.removePreference(categories, currentOption);
      } else {
        preferencesNotifier.addPreference(
            categories,
            category == letteredSizeIcons
                ? category.keys
                    .toList()[index]
                    .toString()
                    .split('.')
                    .last
                    .toUpperCase()
                : category.keys
                    .toList()[index]
                    .toString()
                    .split('.')
                    .last
                    .capitalize);
      }
    });
  }

  //GPT generated function for extracting and formatting names of enums from a map
  String _getText(Map<Enum, FaIcon> category, int index) {
    return category == letteredSizeIcons
        ? category.keys.toList()[index].toString().split('.').last.toUpperCase()
        : category.keys.toList()[index].toString().split('.').last.capitalize;
  }

  @override
  Widget build(BuildContext context) {
    //GPT used for tracking changes via provider
    final userManager = context.watch<UserManager>();
    final preferencesNotifier = userManager.currentUser.preferences;
    Map<Enum, FaIcon> category = _pickCategory(categories);
    List<String> preferences = preferencesNotifier.getPreferences(categories);

    return GradientBackground(
      child: Scaffold(
        backgroundColor: Colors.transparent,
        bottomNavigationBar: const CustomBottomNavBar(
          currentIndex: 3,
        ),
        appBar: const PreferredSize(
          preferredSize: Size.fromHeight(50),
          child: CustomTopAppBar(),
        ),
        //Layout builder generated by GPT for handling amount of preferences per row
        //based on device width
        body: LayoutBuilder(
          builder: (context, constraints) {
            // Define grid column count based on available width
            int crossAxisCount = constraints.maxWidth > 800
                ? 7
                : constraints.maxWidth > 400
                    ? 3
                    : 2;
            return Stack(
              children: [
                SingleChildScrollView(
                  child: Center(
                    child: Column(
                      children: [
                        Padding(
                          padding: const EdgeInsets.only(top: 15),
                          child: Text(
                            "Select $categories",
                            style: Theme.of(context).textTheme.headlineMedium,
                          ),
                        ),
                        Padding(
                          padding: const EdgeInsets.only(
                              top: 10, left: 10, right: 10),
                          child: GridView.builder(
                            physics: const NeverScrollableScrollPhysics(),
                            shrinkWrap: true,
                            gridDelegate:
                                SliverGridDelegateWithFixedCrossAxisCount(
                              crossAxisCount: crossAxisCount,
                              mainAxisSpacing: 8,
                              crossAxisSpacing: 8,
                            ),
                            itemBuilder: (_, index) => GridTile(
                              child: GestureDetector(
                                onLongPress: () {
                                  _handlePress(
                                      index,
                                      category,
                                      //GPT used to create _getText method
                                      _getText(category, index),
                                      preferencesNotifier,
                                      preferences);
                                },
                                onTap: () {
                                  _handlePress(
                                      index,
                                      category,
                                      _getText(category, index),
                                      preferencesNotifier,
                                      preferences);
                                },
                                child: Container(
                                  decoration: BoxDecoration(
                                    color: preferences.contains(
                                      _getText(category, index),
                                    )
                                        ? Theme.of(context).hoverColor
                                        : Colors.transparent,
                                    borderRadius: BorderRadius.circular(10),
                                    boxShadow: [
                                      //GPT used for box shadow styling
                                      BoxShadow(
                                        color: Colors.black.withOpacity(0.25),
                                        spreadRadius: 2,
                                        blurRadius: 6,
                                        offset: const Offset(0, 4),
                                      ),
                                    ],
                                  ),
                                  child: Column(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: [
                                      //Condition contains multiple words and requires special formatting
                                      Text(
                                          _getText(category, index) ==
                                                  "Newwithtags"
                                              ? "New with tags"
                                              : _getText(category, index) ==
                                                      "Newnotags"
                                                  ? "New no tags"
                                                  : _getText(category, index) ==
                                                          "Likenew"
                                                      ? "Like new"
                                                      : _getText(category,
                                                                  index) ==
                                                              "Wellworn"
                                                          ? "Well worn"
                                                          : _getText(
                                                              category, index),
                                          style: Theme.of(context)
                                              .textTheme
                                              .bodyLarge),
                                      IconButton(
                                        icon: category.values.toList()[index],
                                        onPressed: () {
                                          _handlePress(
                                              index,
                                              category,
                                              _getText(category, index),
                                              preferencesNotifier,
                                              preferences);
                                        },
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ),
                            itemCount: category.values.toList().length,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(bottom: 25),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.end,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Center(
                        child: FloatingActionButton(
                          onPressed: () {
                            setState(() {
                              Navigator.pushNamed(
                                  context, '/view_clothes_preferences');
                            });
                          },
                          child: Text(
                            "Save",
                            style: Theme.of(context).textTheme.bodyLarge,
                          ),
                        ),
                      )
                    ],
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}

//GPT used for icon generation and size based on enums provided
const double iconSize = kIsWeb ? 65 : 35;

const Map<LetteredSize, FaIcon> letteredSizeIcons = {
  LetteredSize.xxs: FaIcon(FontAwesomeIcons.ruler, size: iconSize),
  LetteredSize.xs: FaIcon(FontAwesomeIcons.ruler, size: iconSize),
  LetteredSize.s: FaIcon(FontAwesomeIcons.ruler, size: iconSize),
  LetteredSize.m: FaIcon(FontAwesomeIcons.ruler, size: iconSize),
  LetteredSize.l: FaIcon(FontAwesomeIcons.ruler, size: iconSize),
  LetteredSize.xl: FaIcon(FontAwesomeIcons.ruler, size: iconSize),
  LetteredSize.xxl: FaIcon(FontAwesomeIcons.ruler, size: iconSize),
};

Map<ClothingCategory, FaIcon> clothingCategoryIcons = {
  ClothingCategory.top: const FaIcon(FontAwesomeIcons.shirt, size: iconSize),
  ClothingCategory.bottom:
      const FaIcon(FontAwesomeIcons.personRunning, size: iconSize),
  ClothingCategory.accessories:
      const FaIcon(FontAwesomeIcons.blackTie, size: iconSize),
};

Map<ClothingColour, FaIcon> clothingColourIcons = {
  ClothingColour.red: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.red),
  ClothingColour.green: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.green),
  ClothingColour.lightBlue: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.lightBlue),
  ClothingColour.darkBlue: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.blueAccent),
  ClothingColour.purple: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.purple),
  ClothingColour.pink: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.pink),
  ClothingColour.orange: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.orange),
  ClothingColour.yellow: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.yellow),
  ClothingColour.white: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.white),
  ClothingColour.black: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.black),
  ClothingColour.lightGrey: FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.grey[300]),
  ClothingColour.darkGrey: FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.grey[800]),
  ClothingColour.brown: const FaIcon(FontAwesomeIcons.solidCircle,
      size: iconSize, color: Colors.brown),
};

const Map<ClothingType, FaIcon> clothingTypeIcons = {
  //Accessories 0-5
  ClothingType.hat: FaIcon(FontAwesomeIcons.hatCowboy, size: iconSize),
  ClothingType.tie: FaIcon(FontAwesomeIcons.blackTie, size: iconSize),
  ClothingType.belt: FaIcon(FontAwesomeIcons.tape, size: iconSize),
  ClothingType.scarf: FaIcon(FontAwesomeIcons.ribbon, size: iconSize),
  ClothingType.gloves: FaIcon(FontAwesomeIcons.mitten, size: iconSize),
  ClothingType.shoes: FaIcon(FontAwesomeIcons.shoePrints, size: iconSize),
  //Top half 6-12
  ClothingType.jumper: FaIcon(FontAwesomeIcons.wind, size: iconSize),
  ClothingType.shirt: FaIcon(FontAwesomeIcons.shirt, size: iconSize),
  ClothingType.jacket: FaIcon(FontAwesomeIcons.wind, size: iconSize),
  ClothingType.vest: FaIcon(FontAwesomeIcons.vest, size: iconSize),
  ClothingType.coat: FaIcon(FontAwesomeIcons.wind, size: iconSize),
  ClothingType.midriff: FaIcon(FontAwesomeIcons.shirt, size: iconSize),
  ClothingType.dress: FaIcon(FontAwesomeIcons.personDress, size: iconSize),

  //Bottom half 13-17
  ClothingType.skirt: FaIcon(FontAwesomeIcons.personDress, size: iconSize),
  ClothingType.pants: FaIcon(FontAwesomeIcons.personRunning, size: iconSize),
  ClothingType.leggings: FaIcon(FontAwesomeIcons.personDress, size: iconSize),
  ClothingType.shorts: FaIcon(FontAwesomeIcons.personRunning, size: iconSize),
};

const Map<ClothingType, FaIcon> clothingAccessoriesIcons = {
  ClothingType.hat: FaIcon(FontAwesomeIcons.hatCowboy, size: iconSize),
  ClothingType.tie: FaIcon(FontAwesomeIcons.blackTie, size: iconSize),
  ClothingType.belt: FaIcon(FontAwesomeIcons.tape, size: iconSize),
  ClothingType.scarf: FaIcon(FontAwesomeIcons.ribbon, size: iconSize),
  ClothingType.gloves: FaIcon(FontAwesomeIcons.mitten, size: iconSize),
  ClothingType.shoes: FaIcon(FontAwesomeIcons.shoePrints, size: iconSize),
};

const Map<ClothingType, FaIcon> clothingBottomIcons = {
  ClothingType.skirt: FaIcon(FontAwesomeIcons.personDress, size: iconSize),
  ClothingType.pants: FaIcon(FontAwesomeIcons.personRunning, size: iconSize),
  ClothingType.leggings: FaIcon(FontAwesomeIcons.personDress, size: iconSize),
  ClothingType.shorts: FaIcon(FontAwesomeIcons.personRunning, size: iconSize),
};

const Map<ClothingType, FaIcon> clothingTopIcons = {
  ClothingType.jumper: FaIcon(FontAwesomeIcons.wind, size: iconSize),
  ClothingType.shirt: FaIcon(FontAwesomeIcons.shirt, size: iconSize),
  ClothingType.jacket: FaIcon(FontAwesomeIcons.wind, size: iconSize),
  ClothingType.vest: FaIcon(FontAwesomeIcons.vest, size: iconSize),
  ClothingType.coat: FaIcon(FontAwesomeIcons.wind, size: iconSize),
  ClothingType.midriff: FaIcon(FontAwesomeIcons.shirt, size: iconSize),
  ClothingType.dress: FaIcon(FontAwesomeIcons.personDress, size: iconSize),
  ClothingType.sweater: FaIcon(FontAwesomeIcons.wind, size: iconSize),
};

const Map<ClothingCondition, FaIcon> clothingConditionIcons = {
  ClothingCondition.newWithTags: FaIcon(FontAwesomeIcons.tag, size: iconSize),
  ClothingCondition.newNoTags:
      FaIcon(FontAwesomeIcons.solidStar, size: iconSize),
  ClothingCondition.likeNew:
      FaIcon(FontAwesomeIcons.solidHeart, size: iconSize),
  ClothingCondition.worn: FaIcon(FontAwesomeIcons.wrench, size: iconSize),
  ClothingCondition.wellWorn: FaIcon(FontAwesomeIcons.gears, size: iconSize),
};

const Map<ClothingGender, FaIcon> clothingGenderIcons = {
  ClothingGender.male: FaIcon(FontAwesomeIcons.mars, size: iconSize),
  ClothingGender.female: FaIcon(FontAwesomeIcons.venus, size: iconSize),
  ClothingGender.unisex: FaIcon(FontAwesomeIcons.venusMars, size: iconSize),
};
