import 'package:clothing_swap/widgets/custom_bottom_nav_bar.dart';
import 'package:clothing_swap/widgets/custom_top_app_bar.dart';
import 'package:flutter/material.dart';
import 'package:flutter_card_swiper/flutter_card_swiper.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:tutorial_coach_mark/tutorial_coach_mark.dart';
import 'package:clothing_swap/features/clothing/presentation/clothing_item.dart';
import 'package:clothing_swap/features/clothing/presentation/clothing_item_build.dart';
import 'package:toastification/toastification.dart';
import 'package:shared_preferences/shared_preferences.dart';

class SwipePageTop extends StatefulWidget {
  const SwipePageTop({super.key});

  @override
  State<SwipePageTop> createState() => _SwipePageTopState();
}

class _SwipePageTopState extends State<SwipePageTop> {
  //use this for indexing queries/views
  late TutorialCoachMark explainer;
  List<TargetFocus> listTargets = [];
  int _counter = 0;
  bool _hasRun = false;
//Start Chat GPT
  @override
  void initState() {
    super.initState();
    _checkIfRun().then((_) {
      if (!_hasRun) {
        createTutorial();
        showTutorial();
      }
    });
  }

  Future<void> _checkIfRun() async {
    final prefs = await SharedPreferences.getInstance();
    _hasRun = prefs.getBool('hasRun') ?? false;

    if (!_hasRun) {
      // Run your code here
      await prefs.setBool('hasRun', true);
    }
  }

//End ChatGPT
  List swipeImages = [
    ClothingItem(name: 'Jacob', location: 'Mount Cotton', images: [
      'lib/images/0.jpg',
      'lib/images/watermelon.png',
      'lib/images/watermelon2.jpg'
    ]),
    ClothingItem(name: 'Steve', location: 'Brisbane', images: [
      'lib/images/1.jpg',
      'lib/images/watermelon.png',
      'lib/images/watermelon2.jpg'
    ]),
    ClothingItem(name: 'Bob', location: 'Gold Coast', images: [
      'lib/images/2.jpg',
      'lib/images/watermelon.png',
      'lib/images/watermelon2.jpg'
    ]),
    ClothingItem(name: 'Pop', location: 'Sunshine Coast', images: [
      'lib/images/backdrop.jpg',
      'lib/images/watermelon.png',
      'lib/images/watermelon2.jpg'
    ]),
    ClothingItem(name: 'Shaq', location: 'Los Angeles', images: [
      'lib/images/backdrop2.jpg',
      'lib/images/watermelon.png',
      'lib/images/watermelon2.jpg'
    ]),
  ];

  //Fun Facts List Generated By Chat GPT
  List popups = [
    "Fast fashion encourages rapid production of inexpensive clothing to meet current trends, often leading to poor quality and short-lived garments.",
    "The fast fashion industry contributes significantly to environmental pollution, with large amounts of waste and water usage involved in production processes.",
    "Garment workers in the fast fashion industry often face poor working conditions, low wages, and lack of job security, particularly in developing countries.",
    "Fast fashion relies on a quick turnaround of new styles, leading to overconsumption and a culture of discarding clothes after only a few wears.",
    "The production of fast fashion items typically involves harmful chemicals and dyes that can contaminate water sources and harm ecosystems.",
    "Fast fashion brands frequently use non-renewable resources and synthetic fibers, which contribute to increased carbon emissions and environmental degradation.",
    "The low cost of fast fashion often results from the exploitation of labor and outsourcing production to countries with less stringent labor laws and environmental regulations.",
    "The industry's emphasis on trends and seasonal collections encourages consumers to purchase more clothing than needed, contributing to a throwaway culture.",
    "Fast fashion has been linked to significant increases in landfills and waste due to the high turnover rate of clothing and the low durability of garments.",
    "Efforts to combat fast fashion include promoting sustainable fashion practices, such as buying secondhand, supporting ethical brands, and adopting a minimalist wardrobe approach."
  ];
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    if (_counter == swipeImages.length) {
      _counter = 0;
    }
    if (_counter % 4 == 0 && _counter != 0) {
      //_showAlertDialog(context, _counter);
    }
  }

  final GlobalKey _tapingKey = GlobalKey();
  final GlobalKey _moreDetailKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    double height = MediaQuery.of(context).size.height;
    double width = MediaQuery.of(context).size.width;

    return Scaffold(
        bottomNavigationBar: const CustomBottomNavBar(
          currentIndex: 1,
        ),
        appBar: const PreferredSize(
          preferredSize: Size.fromHeight(50),
          child: CustomTopAppBar(),
        ),
        body: Stack(
          alignment: Alignment.center,
          children: [
            Positioned.fill(
              child: Opacity(
                opacity: 0.10,
                child:
                    Image.asset('lib/images/backdrop3.jpg', fit: BoxFit.cover),
              ),
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                Padding(
                  padding: const EdgeInsets.only(top: (10)),
                  child: Container(
                    key: _tapingKey,
                    color: Theme.of(context)
                        .scaffoldBackgroundColor
                        .withOpacity(0.9),
                    width: (kIsWeb) ? width * 0.50625 : width * 0.9125,
                    height: (kIsWeb) ? height * 0.675 : height * 0.58,
                  ),
                ),
              ],
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                Padding(
                  padding: const EdgeInsets.only(),
                  child: SizedBox(
                    height: (kIsWeb) ? height * 0.7 : height * 0.6,
                    width: (kIsWeb) ? width * 0.525 : width * 0.925,
                    child: CardSwiper(
                      cardsCount: swipeImages.length,
                      scale: 0.6,
                      numberOfCardsDisplayed: 3,
                      onSwipe: (previousIndex, currentIndex, direction) {
                        _incrementCounter();

                        if (direction.name == 'right') {
                          //modified from pubdev toastification package
                          toastification.showCustom(
                            context: context,
                            autoCloseDuration: const Duration(seconds: 3),
                            alignment: Alignment.bottomRight,
                            builder: (BuildContext context,
                                ToastificationItem holder) {
                              return Container(
                                decoration: BoxDecoration(
                                  borderRadius: BorderRadius.circular(8),
                                  color: Theme.of(context).hoverColor,
                                ),
                                padding: const EdgeInsets.all(16),
                                margin: const EdgeInsets.all(8),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    const Text('You\'ve got a New Match!',
                                        style: TextStyle(
                                            fontWeight: FontWeight.bold)),
                                    const SizedBox(height: 16),
                                    Row(
                                      children: [
                                        ElevatedButton(
                                          onPressed: () {
                                            Navigator.pushNamed(
                                                context, '/chat');
                                          },
                                          child: const Text('Message Now!'),
                                        ),
                                      ],
                                    ),
                                  ],
                                ),
                              );
                            },
                          );
                        }
                        return true;
                      },
                      allowedSwipeDirection: const AllowedSwipeDirection.only(
                          left: true, right: true),
                      cardBuilder: (context, index, percentThresholdX,
                          percentThresholdY) {
                        final safeIndex = index % swipeImages.length;
                        return ClothingCard(item: swipeImages[safeIndex]);
                      },
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(left: 20, top: 10),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        swipeImages[_counter].name,
                        style: Theme.of(context).textTheme.headlineMedium,
                      ),
                    ],
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(left: 20),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(swipeImages[_counter].location,
                          style: Theme.of(context).textTheme.headlineMedium),
                    ],
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(bottom: (5.0)),
                  child: IconButton(
                      icon: const Icon(Icons.swipe_up),
                      iconSize: 35,
                      key: _moreDetailKey,
                      onPressed: () {
                        Navigator.pushNamed(context, '/clothing_detail');
                      }),
                ),
              ],
            ),
          ],
        ));
  }

//https://github.com/djshah17/Flutter-Tutorial-Coach-Mark-Sample/blob/master/lib/my_tutorial_coach_mark_screen.dart
//Tutorial Code modified for our application
  void createTutorial() {
    listTargets.add(
      TargetFocus(
        color: const Color.fromARGB(255, 69, 65, 65),
        identify: "Target 2",
        keyTarget: _tapingKey,
        contents: [
          TargetContent(
            child: const Column(children: [
              Padding(
                padding: EdgeInsets.only(bottom: (0.0)),
                child: Text(
                    "1. Swipe Left if you're not interested\n2. Swipe Right if you're interested\n3. Tap to view more images",
                    textAlign: TextAlign.justify,
                    style: TextStyle(fontSize: 22, color: Colors.white)),
              ),
            ]),
          )
        ],
        shape: ShapeLightFocus.RRect,
        radius: 5,
      ),
    );

    listTargets.add(TargetFocus(
      color: const Color.fromARGB(255, 69, 65, 65),
      identify: "Target 3",
      keyTarget: _moreDetailKey,
      contents: [
        TargetContent(
            child: const Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              "Swipe or Tap up for more info",
              style: TextStyle(fontSize: 22, color: Colors.white),
              textAlign: TextAlign.end,
            ),
          ],
        )),
      ],
      shape: ShapeLightFocus.Circle,
    ));
  }

  void showTutorial() {
    explainer = TutorialCoachMark(
      targets: listTargets,
      colorShadow: Colors.white,
      hideSkip: true,
      paddingFocus: 1,
      opacityShadow: 0.95,
      onClickTarget: (target) {},
      onClickOverlay: (target) {},
    )..show(context: context);
  }
}
