import 'package:clothing_swap/widgets/custom_bottom_nav_bar.dart';
import 'package:clothing_swap/widgets/custom_top_app_bar.dart';
import 'package:flutter/material.dart';
import 'package:flutter_card_swiper/flutter_card_swiper.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flip_card/flip_card.dart';
import 'package:tutorial_coach_mark/tutorial_coach_mark.dart';

class SwipePageTop extends StatefulWidget {
  const SwipePageTop({super.key});

  @override
  State<SwipePageTop> createState() => _SwipePageTopState();
}

class _SwipePageTopState extends State<SwipePageTop> {
  //use this for indexing queries/views
  late TutorialCoachMark explainer;
  List<TargetFocus> listTargets = [];
  int _counter = 0;
  int _currentSide = 0;
  List images = [
    Image.asset('lib/images/0.jpg', fit: BoxFit.fill),
    Image.asset('lib/images/1.jpg', fit: BoxFit.fill),
    Image.asset('lib/images/2.jpg', fit: BoxFit.fill),
  ];

  List images2 = [
    Image.asset('lib/images/watermelon.png', fit: BoxFit.fill),
    Image.asset('lib/images/person.png', fit: BoxFit.fill)
  ];
  //Picking Random Fun fact

  //Fun Facts List Generated By Chat GPT
  List popups = [
    "Fast fashion encourages rapid production of inexpensive clothing to meet current trends, often leading to poor quality and short-lived garments.",
    "The fast fashion industry contributes significantly to environmental pollution, with large amounts of waste and water usage involved in production processes.",
    "Garment workers in the fast fashion industry often face poor working conditions, low wages, and lack of job security, particularly in developing countries.",
    "Fast fashion relies on a quick turnaround of new styles, leading to overconsumption and a culture of discarding clothes after only a few wears.",
    "The production of fast fashion items typically involves harmful chemicals and dyes that can contaminate water sources and harm ecosystems.",
    "Fast fashion brands frequently use non-renewable resources and synthetic fibers, which contribute to increased carbon emissions and environmental degradation.",
    "The low cost of fast fashion often results from the exploitation of labor and outsourcing production to countries with less stringent labor laws and environmental regulations.",
    "The industry's emphasis on trends and seasonal collections encourages consumers to purchase more clothing than needed, contributing to a throwaway culture.",
    "Fast fashion has been linked to significant increases in landfills and waste due to the high turnover rate of clothing and the low durability of garments.",
    "Efforts to combat fast fashion include promoting sustainable fashion practices, such as buying secondhand, supporting ethical brands, and adopting a minimalist wardrobe approach."
  ];
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    if (_counter % 8 == 0) {
      _showAlertDialog(context, _counter);
    }
  }

//https://github.com/djshah17/Flutter-Tutorial-Coach-Mark-Sample/blob/master/lib/my_tutorial_coach_mark_screen.dart
//Code modified for our application
  final GlobalKey _tapingKey = GlobalKey();
  final GlobalKey _moreDetailKey = GlobalKey();

  @override
  void initState() {
    createTutorial();
    //showTutorial();
    super.initState();
  }

  void _flipCard() {
    setState(() {
      if ((_currentSide + 1) >= images2.length) {
        _currentSide = 0;
      } else {
        _currentSide = _currentSide + 1;
      }
    });
  }

  void _showAlertDialog(BuildContext context, int counter) {
    showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            backgroundColor: Colors.lightBlue,
            title: Text('Fun Fact',
                style: Theme.of(context).textTheme.headlineMedium),
            //Have 10 fun facts and index with mod to avoid out of bounds
            content: Text(
              popups[counter % 10],
              style: const TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
            actions: [
              TextButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: Text(
                  'Sweet!',
                  style: Theme.of(context).textTheme.headlineMedium,
                ),
              ),
            ],
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    double height = MediaQuery.of(context).size.height;
    double width = MediaQuery.of(context).size.width;

    return Scaffold(
      bottomNavigationBar: const CustomBottomNavBar(
        currentIndex: 1,
      ),
      appBar: const PreferredSize(
        preferredSize: Size.fromHeight(50),
        child: CustomTopAppBar(),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: (10.0)),
            child: SizedBox(
              height: (kIsWeb) ? height * 0.65 : height * 0.6,
              width: (kIsWeb) ? width * 0.6 : width * 0.925,
              child: CardSwiper(
                cardsCount: 3,
                numberOfCardsDisplayed: 3,
                onSwipe: (previousIndex, currentIndex, direction) {
                  _incrementCounter();
                  if (direction.name == 'right') {
                    Navigator.pushNamed(context, '/match_animation');
                  }
                  return true;
                },
                allowedSwipeDirection:
                    const AllowedSwipeDirection.only(left: true, right: true),
                cardBuilder:
                    (context, index, percentThresholdX, percentThresholdY) =>
                        FlipCard(
                            key: _tapingKey,
                            onFlip: _flipCard,
                            //key: Key('flip$index'),
                            direction: FlipDirection.HORIZONTAL,
                            front: images[index],
                            back: images2[_currentSide]),
              ),
            ),
          ),
          SizedBox(
            height: !(kIsWeb) ? height * 0.004 : null,
          ),
          Padding(
            padding: const EdgeInsets.only(left: 10, right: 10),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Steve$_counter',
                  style: Theme.of(context).textTheme.headlineLarge,
                  textAlign: TextAlign.left,
                ),
                const Text(
                  '',
                ),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(left: 10, right: 10),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Mount Cotton',
                  style: Theme.of(context).textTheme.headlineMedium,
                  textAlign: TextAlign.left,
                ),
                const Text(
                  '',
                ),
              ],
            ),
          ),
          IconButton(
              icon: const Icon(Icons.arrow_circle_up),
              iconSize: 35,
              key: _moreDetailKey,
              color: Colors.white,
              onPressed: () {
                Navigator.pushNamed(context, '/clothing_detail');
              }),
        ],
      ),
    );
  }

  void createTutorial() {
    listTargets.add(
      TargetFocus(
        color: Colors.green,
        identify: "Target 2",
        keyTarget: _tapingKey,
        contents: [
          TargetContent(
            align: ContentAlign.bottom,
            child: const Center(
              child: Text(
                "Swipe left: not interested\n Swipe right: interested\nTap: See more images",
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 22,
                  color: Colors.white,
                ),
              ),
            ),
          )
        ],
        shape: ShapeLightFocus.RRect,
        radius: 7,
      ),
    );

    listTargets.add(TargetFocus(
      color: Colors.green,
      identify: "Target 3",
      keyTarget: _moreDetailKey,
      contents: [
        TargetContent(
            align: ContentAlign.bottom,
            child: const Column(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                Text(
                  "Swipe/Tap up for more info",
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 22,
                    color: Colors.white,
                  ),
                ),
              ],
            )),
      ],
      shape: ShapeLightFocus.Circle,
    ));
  }

  void showTutorial() {
    explainer = TutorialCoachMark(
      targets: listTargets,
      colorShadow: Colors.white,
      textSkip: "SKIP",
      textStyleSkip: const TextStyle(fontSize: 20, color: Colors.white),
      paddingFocus: 4,
      opacityShadow: 1,
      onClickTarget: (target) {},
      onClickOverlay: (target) {},
    )..show(context: context);
  }
}
