import 'dart:io';
import 'package:clothing_swap/features/profile/presentation/profile_class.dart';
import 'package:clothing_swap/theme/gradient.dart';
import 'package:clothing_swap/widgets/browse_photos.dart';
import 'package:clothing_swap/widgets/custom_bottom_nav_bar.dart';
import 'package:clothing_swap/widgets/custom_top_app_bar.dart';
import 'package:clothing_swap/widgets/photo_modal.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:image_picker/image_picker.dart';
import 'package:provider/provider.dart';
import 'package:reorderable_grid_view/reorderable_grid_view.dart';

class PersonalProfile extends StatefulWidget {
  const PersonalProfile({super.key});

  @override
  State<PersonalProfile> createState() => _PersonalProfileState();
}

class _PersonalProfileState extends State<PersonalProfile> {
  void _showAlertDialogRemoveListing(
      BuildContext context, personalProfile, index) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          backgroundColor: Colors.blue,
          title: const Text('Remove Listings'),
          content: const Text('Are you sure you want to remove this listing?'),
          actions: [
            TextButton(
              onPressed: () {
                setState(() {
                  personalProfile.personalListings.removeAt(index);
                });
              },
              //Gpt for styling button
              style: TextButton.styleFrom(
                  foregroundColor: Colors.white // Set the text color here
                  ),
              child: const Text('Delete'),
            ),
            TextButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              //Gpt for styling button
              style: TextButton.styleFrom(
                  foregroundColor: Colors.white // Set the text color here
                  ),
              child: const Text('Cancel'),
            ),
          ],
        );
      },
    );
  }

  bool edited = false;

  final _changeBio = TextEditingController();

  final ImagePicker _picker = ImagePicker();
  XFile? _image;

  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    final userManager = Provider.of<UserManager>(context);
    final personalProfile = userManager.currentUser;

    return GradientBackground(
        child: Scaffold(
      backgroundColor: Colors.transparent,
      bottomNavigationBar: const CustomBottomNavBar(
        currentIndex: 3,
      ),
      appBar: const PreferredSize(
        preferredSize: Size.fromHeight(50),
        child: CustomTopAppBar(),
      ),
      //Layout builder generated by ChatGPT
      body: LayoutBuilder(
        builder: (context, constraints) {
          // Define grid column count based on available width
          int crossAxisCount = constraints.maxWidth > 600
              ? 4
              : constraints.maxWidth > 400
                  ? 2
                  : 2;

          return Center(
            child: SingleChildScrollView(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Padding(
                        padding: const EdgeInsets.only(top: 5.0, bottom: 5),
                        child: SizedBox(
                            height: 150,
                            width: 200,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 25,
                                  child: CircleAvatar(
                                    radius: 75,
                                    backgroundImage: (_image == null)
                                        ? personalProfile.profilePicture
                                        : kIsWeb
                                            ? Image.network(_image!.path,
                                                    fit: BoxFit.cover)
                                                .image
                                            : FileImage(
                                                (File(
                                                  _image!.path,
                                                )),
                                              ),
                                  ),
                                ),
                                Positioned(
                                  right: 0,
                                  bottom: 0,
                                  child: Padding(
                                    padding: const EdgeInsets.only(left: 10),
                                    child: IconButton(
                                      icon: Icon(
                                          edited ? Icons.check : Icons.edit),
                                      onPressed: () {
                                        edited = !edited;
                                        setState(() {
                                          personalProfile.updateProfile(
                                              newBio: _changeBio.text);
                                        });
                                      },
                                    ),
                                  ),
                                ),
                              ],
                            )),
                      ),
                      Visibility(
                        visible: edited,
                        child: IconButton(
                            icon: const Icon(
                              Icons.image,
                            ),
                            iconSize: 25,
                            onPressed: () async {
                              XFile? image = await photoOptionModal(
                                  context, _picker, 50, null, null);
                              setState(() {
                                _image = image;
                              });
                            }),
                      ),
                    ],
                  ),
                  Stack(
                    children: [
                      SizedBox(
                        height: 50,
                        width: 375,
                        child: Text(
                          personalProfile.name,
                          style: Theme.of(context).textTheme.headlineLarge,
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ],
                  ),
                  Padding(
                      padding: const EdgeInsets.only(top: 5, bottom: 15),
                      child: Stack(
                        children: [
                          Stack(children: [
                            Visibility(
                              visible: !edited,
                              child: Padding(
                                padding: const EdgeInsets.only(bottom: 15),
                                child: SizedBox(
                                  width: width * 0.85,
                                  child: Text(
                                    personalProfile.bio,
                                    style:
                                        Theme.of(context).textTheme.bodyLarge,
                                    textAlign: TextAlign.center,
                                    softWrap: true,
                                  ),
                                ),
                              ),
                            ),
                          ]),
                          Visibility(
                            visible: edited,
                            child: SizedBox(
                              height: 75,
                              width: 300,
                              child: TextField(
                                maxLines: 3,
                                maxLength: 50,
                                textAlignVertical: TextAlignVertical.top,
                                controller: _changeBio,
                                decoration: InputDecoration(
                                  contentPadding: kIsWeb
                                      ? const EdgeInsets.all(20.0)
                                      : const EdgeInsets.only(
                                          top: 10, left: 10),
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(15),
                                  ),
                                  hintText: 'New Bio...',
                                  filled: true,
                                  //GPT for fill color
                                  fillColor: Theme.of(context).highlightColor,
                                ),
                              ),
                            ),
                          ),
                        ],
                      )),
                  Padding(
                    padding: const EdgeInsets.only(top: kIsWeb ? 15 : 5),
                    child: Visibility(
                      visible: !edited,
                      child: GridView.builder(
                        physics: const NeverScrollableScrollPhysics(),
                        shrinkWrap: true,
                        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                          crossAxisCount: crossAxisCount,
                          mainAxisSpacing: 1.5,
                          crossAxisSpacing: 1.5,
                        ),
                        itemBuilder: (_, index) => GridTile(
                          child: GestureDetector(
                            onLongPress: () {
                              edited = !edited;
                              setState(() {});
                            },
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => BrowsePhoto(
                                          title: "personal",
                                          gridIndex: index,
                                          photoListings: personalProfile
                                              .personalListings
                                              .map((item) => item
                                                      .images.isNotEmpty
                                                  ? item.images[0]
                                                  : const AssetImage(
                                                      'lib/images/noImage.png'))
                                              .toList(),
                                        )),
                              );
                            },
                            child: Image(
                              image: personalProfile
                                      .personalListings[index].images.isNotEmpty
                                  ? personalProfile
                                      .personalListings[index].images[0]
                                  : const AssetImage('lib/images/noImage.png'),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                        itemCount: personalProfile.personalListings.length,
                      ),
                    ),
                  ),
                  Padding(
                      padding: const EdgeInsets.only(top: kIsWeb ? 15 : 5),
                      child: Visibility(
                        visible: edited,
                        child: ReorderableGridView.builder(
                          physics: const NeverScrollableScrollPhysics(),
                          shrinkWrap: true,
                          dragStartDelay: Duration.zero,
                          onReorder: (oldIndex, newIndex) {
                            setState(() {
                              var val = personalProfile.personalListings
                                  .removeAt(oldIndex);
                              personalProfile.personalListings
                                  .insert(newIndex, val);
                            });
                          },
                          gridDelegate:
                              SliverGridDelegateWithFixedCrossAxisCount(
                            crossAxisCount: crossAxisCount,
                            mainAxisSpacing: 0,
                            crossAxisSpacing: 0,
                          ),
                          itemBuilder: (_, index) => GridTile(
                              key: ValueKey(
                                  personalProfile.personalListings[index]),
                              child: Stack(
                                children: [
                                  SizedBox(
                                    width: double.infinity,
                                    height: double.infinity,
                                    child: Image(
                                      image: personalProfile
                                              .personalListings[index]
                                              .images
                                              .isNotEmpty
                                          ? personalProfile
                                              .personalListings[index].images[0]
                                          : const AssetImage(
                                              'lib/images/noImage.png'),
                                      fit: BoxFit.cover,
                                    ),
                                  ),
                                  Row(
                                    mainAxisAlignment:
                                        MainAxisAlignment.spaceBetween,
                                    children: [
                                      IconButton(
                                        icon: const Icon(
                                          Icons.remove_circle,
                                          color: Colors.black,
                                        ),
                                        iconSize: 25,
                                        onPressed: () async {
                                          _showAlertDialogRemoveListing(
                                              context, personalProfile, index);
                                        },
                                      ),
                                      IconButton(
                                        icon: const Icon(
                                          Icons.open_with,
                                          color: Colors.black,
                                        ),
                                        iconSize: 25,
                                        onPressed: () {},
                                      ),
                                    ],
                                  ),
                                ],
                              )),
                          itemCount: personalProfile.personalListings.length,
                        ),
                      )),
                ],
              ),
            ),
          );
        },
      ),
    ));
  }
}
