// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcJO9sdV07zutb-MDx9anOOFhw9MZT_HU',
    appId: '1:1042663527400:web:b16c3f6b1b052c91a80a5d',
    messagingSenderId: '1042663527400',
    projectId: 'newstyleswap',
    authDomain: 'newstyleswap.firebaseapp.com',
    storageBucket: 'newstyleswap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcBsftiWktD4F2Kp0KYRIRpIMtX1i17I',
    appId: '1:1042663527400:android:d162fba67b1ec2a8a80a5d',
    messagingSenderId: '1042663527400',
    projectId: 'newstyleswap',
    storageBucket: 'newstyleswap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKYBhDPZismpqguqlLlNWI9fSGuR9hTCY',
    appId: '1:1042663527400:ios:3841dd03005b4b45a80a5d',
    messagingSenderId: '1042663527400',
    projectId: 'newstyleswap',
    storageBucket: 'newstyleswap.appspot.com',
    iosBundleId: 'au.rowangray.clothingSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKYBhDPZismpqguqlLlNWI9fSGuR9hTCY',
    appId: '1:1042663527400:ios:3841dd03005b4b45a80a5d',
    messagingSenderId: '1042663527400',
    projectId: 'newstyleswap',
    storageBucket: 'newstyleswap.appspot.com',
    iosBundleId: 'au.rowangray.clothingSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcJO9sdV07zutb-MDx9anOOFhw9MZT_HU',
    appId: '1:1042663527400:web:53f4100ef25b1380a80a5d',
    messagingSenderId: '1042663527400',
    projectId: 'newstyleswap',
    authDomain: 'newstyleswap.firebaseapp.com',
    storageBucket: 'newstyleswap.appspot.com',
  );
}
